name: Release Nightly
on: push
jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
          matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm run release
            - uses: actions/upload-artifact@v3
              with:
                name: Data
                path: |
                    build/*.exe
                    build/*.dmg
                    build/*.rpm
                    build/*.deb
