name: Release Nightly
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[🚀 Release Nightly]')"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GIT_TOKEN }}
                  ref: nightly
            - uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
                  registry-url: "https://registry.npmjs.org"
            - run: git config --global user.name 'Bastian Huber (@basdl)'
            - run: git config --global user.email 'basdl@github.com'
            - run: npm ci
            - run: npm run release
