name: Release Nightly
on: push
jobs:
    build:
        runs-on: ${{ matrix.os }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DEBUG: electron-builder

        strategy:
          matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "17.x"
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: |
                export DEBUG=electron-builder
                export GH_TOKEN=${{ secrets.GH_TOKEN }}
                npm run build-mac
              if: contains(matrix.os, 'macos')
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
            - run: npm run build-lnx
              if: contains(matrix.os, 'ubuntu')
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
            - run: npm run build-win-nsis
              if: contains(matrix.os, 'windows')
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
            - uses: actions/upload-artifact@v3
              with:
                name: Data
                path: |
                    build/*.exe
                    build/*.dmg
                    build/*.rpm
                    build/*.deb
